import topModalOpenClose from "./modules/1_topModalOpenClose";
import classSliderCarousel from "./modules/2_sliderCarouselBenefitsUser";
import classCarousel_service from "./modules/3_sliderCarousel_service";
import modalService from "./modules/4_modalService";
import timer from "./modules/5_timer";
import validationForm from "./modules/6_validationForm";
import sendForm from "./modules/7_sendForm";
import sertDoc from "./modules/8_sertificateDoc";
import smoothScroll from "./modules/9_smoothScroll";
import calculator from "./modules/10_calculator";

topModalOpenClose();
classSliderCarousel();
classCarousel_service();
modalService();
timer('23 september  2021');
validationForm();
sendForm();
sertDoc();
smoothScroll();
calculator();
